import type { EvolutionDef } from '../types';

export const EVOLUTION_DEFS: EvolutionDef[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  //  FOGO — Tema: dano, burn, pressão, execução
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'fire_incinerator',
    name: 'Incineradora',
    element: 'fire',
    icon: '🎯',
    color: '#ff4400',
    description: 'Disparos pesados contra alvos prioritários. Dano bônus em inimigos queimando. Burn forte em alvo único.',
    roleLabel: 'Anti-Elite / Boss Killer',
    strengths: 'Excelente contra elites, golems e bosses. Dano por disparo enorme.',
    weaknesses: 'Lenta para limpar hordas. Pouco eficiente contra grupos espalhados.',
    damageMult: 1.5,
    fireRateMult: 0.6,
    rangeMult: 1.1,
    magicDamageMult: 1.8,
    magicBehaviorId: 'evo_fire_incinerator',
  },
  {
    id: 'fire_flamethrower',
    name: 'Lança-Chamas',
    element: 'fire',
    icon: '🔥',
    color: '#ff8800',
    description: 'Ataque em spray que atinge todos em alcance. Burn fraco em cada alvo. Excelente contra hordas agrupadas.',
    roleLabel: 'Waveclear / Anti-Horda',
    strengths: 'Devastadora contra grupos densos. Ótima em rotas compactas e chokes.',
    weaknesses: 'Alcance reduzido. Pouco dano contra bosses e alvos isolados.',
    damageMult: 0.8,
    fireRateMult: 1.3,
    rangeMult: 0.75,
    magicDamageMult: 0.7,
    magicBehaviorId: 'evo_fire_flamethrower',
  },
  {
    id: 'fire_furnace',
    name: 'Fornalha Viva',
    element: 'fire',
    icon: '♨',
    color: '#cc3300',
    description: 'Cria zonas de calor persistentes no chão. Inimigos na área sofrem dano contínuo. Amplifica burn em inimigos dentro da zona.',
    roleLabel: 'Territorial / Zona de Perigo',
    strengths: 'Excelente em chokes. Ótima contra waves lentas e densas. Forte sinergia com controle.',
    weaknesses: 'Burst baixo. Depende de posicionamento. Ineficiente contra rápidos e isolados.',
    damageMult: 0.9,
    fireRateMult: 1.0,
    rangeMult: 0.9,
    magicDamageMult: 1.0,
    magicBehaviorId: 'evo_fire_furnace',
    magicBarMaxMult: 0.8,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  ÁGUA — Tema: slow, controle, ritmo, debuff, setup
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'water_cryomancer',
    name: 'Criomante',
    element: 'water',
    icon: '❄',
    color: '#88ddff',
    description: 'Slow forte por hit. Acúmulo de magias congela o alvo brevemente. Elites e bosses recebem freeze reduzido.',
    roleLabel: 'Controle Pesado / Anti-Rush',
    strengths: 'Excelente contra rápidos. Enorme valor em waves de ruptura. Ganha tempo para a defesa.',
    weaknesses: 'Dano muito baixo. Depende de outras torres para finalizar.',
    damageMult: 0.7,
    fireRateMult: 1.2,
    rangeMult: 1.0,
    magicDamageMult: 0.6,
    magicBehaviorId: 'evo_water_cryomancer',
  },
  {
    id: 'water_pressure_tide',
    name: 'Maré Pressurizada',
    element: 'water',
    icon: '🌊',
    color: '#2288cc',
    description: 'Projéteis com impacto splash. Dano maior que Criomante com slow moderado. Equilibrada entre dano e controle.',
    roleLabel: 'Ofensiva Equilibrada / Splash',
    strengths: 'Boa contra grupos médios. Controle razoável sem sacrificar dano. Versátil.',
    weaknesses: 'Não controla tão bem quanto Criomante. Não mata tão rápido quanto torres ofensivas.',
    damageMult: 1.3,
    fireRateMult: 1.0,
    rangeMult: 1.0,
    magicDamageMult: 1.2,
    magicBehaviorId: 'evo_water_pressure_tide',
  },
  {
    id: 'water_abyssal_well',
    name: 'Poço Abissal',
    element: 'water',
    icon: '🌀',
    color: '#0066aa',
    description: 'Cria redemoinho que aplica slow e vulnerabilidade (+15% dano recebido). Enfraquece áreas da rota para a defesa inteira.',
    roleLabel: 'Setup / Debuff Territorial',
    strengths: 'Ótima sinergia com splash, fogo e terra. Cria valor para toda a defesa no choke.',
    weaknesses: 'Depende de posicionamento. Dano próprio mediano. Fraca em áreas abertas.',
    damageMult: 0.8,
    fireRateMult: 0.9,
    rangeMult: 1.1,
    magicDamageMult: 1.0,
    magicBehaviorId: 'evo_water_abyssal_well',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  TERRA — Tema: estabilidade, firmeza, dano consistente, suporte
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'earth_ballista',
    name: 'Balista Rochosa',
    element: 'earth',
    icon: '🏹',
    color: '#886622',
    description: 'Disparo pesado de longo alcance. Dano forte e consistente. Projétil pode perfurar e atingir um segundo alvo.',
    roleLabel: 'Anti-Elite / Longo Alcance',
    strengths: 'Excelente contra elites. Consistente e confiável. Ótimo alcance.',
    weaknesses: 'Pouca limpeza de horda. Sem controle. Depende de suporte ao redor.',
    damageMult: 1.5,
    fireRateMult: 0.6,
    rangeMult: 1.4,
    magicDamageMult: 1.6,
    magicBehaviorId: 'evo_earth_ballista',
  },
  {
    id: 'earth_quarry',
    name: 'Pedreira',
    element: 'earth',
    icon: '⛏',
    color: '#668833',
    description: 'Ataque em área ampla. Cada hit aplica micro-lentidão permanente. Pressão consistente em grupos compactos.',
    roleLabel: 'AoE / Pressão de Corredor',
    strengths: 'Muito boa em rotas densas. Excelente contra blocos de inimigos.',
    weaknesses: 'Menos eficiente em alvo único rápido. Cadência mais lenta.',
    damageMult: 0.9,
    fireRateMult: 0.8,
    rangeMult: 0.9,
    magicDamageMult: 1.0,
    magicBehaviorId: 'evo_earth_quarry',
  },
  {
    id: 'earth_monolith',
    name: 'Monólito',
    element: 'earth',
    icon: '🗿',
    color: '#556644',
    description: 'Dano menor, mas emite aura que fortalece torres próximas: +15% dano e +10% velocidade por 5s ao ativar magia.',
    roleLabel: 'Suporte / Buff Posicional',
    strengths: 'Enorme valor em composições densas. Transforma a região em ponto forte.',
    weaknesses: 'Fraca isoladamente. Dano próprio baixo. Depende de sinergia e posição.',
    damageMult: 0.5,
    fireRateMult: 0.8,
    rangeMult: 1.0,
    magicDamageMult: 0.5,
    magicBehaviorId: 'evo_earth_monolith',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  VENTO — Tema: velocidade, cobertura, multi-hit, reposicionamento
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'wind_harpoon',
    name: 'Arpão Tempestivo',
    element: 'wind',
    icon: '⚡',
    color: '#ccee44',
    description: 'Cadência muito alta. Dano menor por hit. Excelente tracking e bônus contra inimigos rápidos.',
    roleLabel: 'DPS Consistente / Anti-Runner',
    strengths: 'Excelente contra goblins, harpias e runners. Muito consistente.',
    weaknesses: 'Burst menor. Pouco impacto contra tanques muito resistentes.',
    damageMult: 0.7,
    fireRateMult: 1.8,
    rangeMult: 1.1,
    magicDamageMult: 0.8,
    magicBehaviorId: 'evo_wind_harpoon',
  },
  {
    id: 'wind_blade_storm',
    name: 'Tempestade de Lâminas',
    element: 'wind',
    icon: '🌪',
    color: '#aaddaa',
    description: 'Projéteis ricocheteiam entre até 4 inimigos. Dano moderado por alvo. Ótima cobertura contra grupos.',
    roleLabel: 'Multi-Target / Waveclear',
    strengths: 'Excelente contra hordas e grupos médios. Cobre bem rotas movimentadas.',
    weaknesses: 'Pior contra boss e alvo único pesado. Depende da posição dos inimigos.',
    damageMult: 0.9,
    fireRateMult: 1.0,
    rangeMult: 1.0,
    magicDamageMult: 0.8,
    magicBehaviorId: 'evo_wind_blade_storm',
  },
  {
    id: 'wind_tactical_cyclone',
    name: 'Ciclone Tático',
    element: 'wind',
    icon: '💨',
    color: '#77ccaa',
    description: 'Ataques aplicam micro-atraso. Magia empurra e desacelera todos em área. Ganha tempo para a defesa.',
    roleLabel: 'Controle / Atraso Tático',
    strengths: 'Excelente para ganhar tempo. Muito bom contra elites perigosos. Ótima sinergia.',
    weaknesses: 'Dano próprio menor. Depende de sinergia com torres ofensivas.',
    damageMult: 0.6,
    fireRateMult: 0.9,
    rangeMult: 1.2,
    magicDamageMult: 0.7,
    magicBehaviorId: 'evo_wind_tactical_cyclone',
  },
];
