import type { FusionDef } from '../types';

export const FUSION_DEFS: FusionDef[] = [
  // Earth primary
  { id:'earth+fire',  name:'Magma',      primaryElement:'earth', secondaryElement:'fire',
    icon:'🌋', color:'#ff6600', roleLabel:'Controle territorial',
    description:'Fissuras de magma irradiam do impacto, criando poças de lava persistentes.',
    magicDamageMult:1.8, specialEffect:'magma_pool',
    magicAnimationId:'fusion_magma' },
  { id:'earth+water', name:'Pântano',    primaryElement:'earth', secondaryElement:'water',
    icon:'🏞', color:'#556b2f', roleLabel:'Debuff/entrap',
    description:'Zona de decadência com raízes que prendem e enfraquecem inimigos.',
    magicDamageMult:1.4, specialEffect:'swamp',
    magicAnimationId:'fusion_swamp' },
  { id:'earth+wind',  name:'Tempestade de Areia', primaryElement:'earth', secondaryElement:'wind',
    icon:'🏜', color:'#daa520', roleLabel:'Anti-horde erosão',
    description:'Espiral abrasiva de areia que erode inimigos com múltiplos hits.',
    magicDamageMult:1.5, specialEffect:'sandstorm',
    magicAnimationId:'fusion_sandstorm' },

  // Fire primary
  { id:'fire+earth',  name:'Bola de Fogo', primaryElement:'fire', secondaryElement:'earth',
    icon:'☄', color:'#ff4400', roleLabel:'Burst AoE',
    description:'Meteoro explosivo com estilhaços que atingem alvos próximos.',
    magicDamageMult:2.0, specialEffect:'fireball_aoe',
    magicAnimationId:'fusion_fireball' },
  { id:'fire+water',  name:'Vapor',       primaryElement:'fire', secondaryElement:'water',
    icon:'♨', color:'#ccaaff', roleLabel:'Debuff amplificador',
    description:'Nuvem de vapor superaquecido que escalda e desorienta inimigos.',
    magicDamageMult:1.6, specialEffect:'steam',
    magicAnimationId:'fusion_steam' },
  { id:'fire+wind',   name:'Inferno',     primaryElement:'fire', secondaryElement:'wind',
    icon:'🔥', color:'#ff2200', roleLabel:'Anti-elite execução',
    description:'Feixe de combustão concentrada — detonação devastadora em alvos feridos.',
    magicDamageMult:1.5, specialEffect:'inferno',
    magicAnimationId:'fusion_inferno' },

  // Water primary
  { id:'water+fire',  name:'Gêiser',      primaryElement:'water', secondaryElement:'fire',
    icon:'⛲', color:'#66ccff', roleLabel:'Burst control',
    description:'Erupção vertical de água fervente que lança inimigos ao ar.',
    magicDamageMult:1.7, specialEffect:'geyser',
    magicAnimationId:'fusion_geyser' },
  { id:'water+earth', name:'Lama',        primaryElement:'water', secondaryElement:'earth',
    icon:'💩', color:'#8b7355', roleLabel:'Anti-rush wall',
    description:'Onda de lama densa com desaceleração composta e terreno pegajoso.',
    magicDamageMult:1.3, specialEffect:'mud',
    magicAnimationId:'fusion_mud' },
  { id:'water+wind',  name:'Nevasca',     primaryElement:'water', secondaryElement:'wind',
    icon:'❄', color:'#aaeeff', roleLabel:'Waveclear + freeze',
    description:'Frente de gelo varrendo que congela progressivamente.',
    magicDamageMult:1.6, specialEffect:'blizzard',
    magicAnimationId:'fusion_blizzard' },

  // Same-element fusions
  { id:'fire+fire',   name:'Núcleo Solar',          primaryElement:'fire',  secondaryElement:'fire',
    icon:'☀', color:'#ffcc00', roleLabel:'Apex ofensivo',
    description:'Esfera solar pulsante com corona de chamas — queimadura eterna.',
    magicDamageMult:2.5, specialEffect:'solar_core',
    magicAnimationId:'fusion_solar_core' },
  { id:'water+water', name:'Vórtice Abissal',        primaryElement:'water', secondaryElement:'water',
    icon:'🌀', color:'#00ccff', roleLabel:'Apex control',
    description:'Redemoinho abissal com centro escuro que suga e afoga inimigos.',
    magicDamageMult:2.3, specialEffect:'abyssal_vortex',
    magicAnimationId:'fusion_abyssal_vortex' },
  { id:'earth+earth', name:'Terremoto Primordial',   primaryElement:'earth', secondaryElement:'earth',
    icon:'🌋', color:'#aacc44', roleLabel:'Apex waveclear',
    description:'Evento sísmico colossal com fissuras radiais e réplicas.',
    magicDamageMult:2.8, specialEffect:'primal_quake',
    magicAnimationId:'fusion_primal_quake' },
  { id:'wind+wind',   name:'Furacão Eterno',         primaryElement:'wind',  secondaryElement:'wind',
    icon:'⚡', color:'#eeff44', roleLabel:'Apex reposition',
    description:'Circulação massiva de vento com anéis concêntricos e detritos orbitais.',
    magicDamageMult:2.2, magicBarMaxMult:2, specialEffect:'eternal_hurricane',
    magicAnimationId:'fusion_eternal_hurricane' },

  // Wind primary (cross-element)
  { id:'wind+fire',   name:'Relâmpago',   primaryElement:'wind', secondaryElement:'fire',
    icon:'⚡', color:'#ffff00', roleLabel:'Chain burst',
    description:'Descarga elétrica em cadeia entre alvos com flash terminal.',
    magicDamageMult:2.2, specialEffect:'lightning',
    magicAnimationId:'fusion_lightning' },
  { id:'wind+water',  name:'Tsunami',     primaryElement:'wind', secondaryElement:'water',
    icon:'🌊', color:'#0077cc', roleLabel:'Macro reset',
    description:'Parede de água varrendo que empurra e deixa terreno molhado.',
    magicDamageMult:1.5, specialEffect:'tsunami',
    magicAnimationId:'fusion_tsunami' },
  { id:'wind+earth',  name:'Tornado',     primaryElement:'wind', secondaryElement:'earth',
    icon:'🌪', color:'#88cc44', roleLabel:'Mobile control',
    description:'Coluna rotacional com detritos que puxa e atordoa brevemente.',
    magicDamageMult:1.8, specialEffect:'tornado',
    magicAnimationId:'fusion_tornado' },
];

export function getFusionDef(primaryElement: string, secondaryElement: string): FusionDef | undefined {
  return FUSION_DEFS.find(f => f.id === `${primaryElement}+${secondaryElement}`);
}
